Desktop Portfolio
Thinus01/Desktop_Portfolio pull request #1
Opened 2022-11-08 10:10 UTC by Thinus01

Desktop portfolio with the introduction, content pages, about section, and a contact form.

2022-11-08 11:17 UTC, Nemwel-Boniface requested changes
## Hello @Thinus01     :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] I have realized that you have only done the desktop version of your project in this milestone. However, kindly note that you are required to work on the desktop version but still maintain the mobile version working as it was before. This said, kindly include the mobile version styling for your website as well.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 11:17 UTC, Nemwel-Boniface commented on index.html
> +            </ul>
- [ ] I have realized that your desktop version menu does not look like the Figma design. Kindly align the elements so that they fit well inside the header container.

**This is how your design looks like:**

![image](https://user-images.githubusercontent.com/86318284/200547896-52b016d8-a4c3-4129-b446-c60a9c7d3a46.png)

**This is the desired design:**

![image](https://user-images.githubusercontent.com/86318284/200548014-189f45fc-6f52-4d67-8bae-1cc294977f7b.png)

2022-11-08 11:17 UTC, Nemwel-Boniface commented on index.html
> +                    </button>
- [ ] Your buttons do not currently match the provided design guidelines. They also lack the provided button states eg on hover, on click etc. Kindly implement this to meet all the project requirements.

**These are the desired button states:**

![image](https://user-images.githubusercontent.com/86318284/200549022-de0a6dbf-e55b-4351-bc6a-dacba984f407.png)

**Note:** Kindly implement this change on all the buttons in your webpage as I have realized that the trend is the same everywhere. Me having to repeatedly point out the same thing would be redundant.

2022-11-08 11:17 UTC, Nemwel-Boniface commented on index.html
> +    <section id="list_portfolio">
- [ ] As per the project design guidelines, this section for the individual projects, are supposed to be in alternating order. One having the image on the left and the immediate under having the image on the right. Kindly ensure that you make this change to meet all the project requirements.

**This is how your design looks like:**

[Screencast from 08-11-2022 02:10:46 ALASIRI.webm](https://user-images.githubusercontent.com/86318284/200549931-a648a793-1532-4c71-b633-cb7e8c160eb0.webm)


**This is the desired design:**

![image](https://user-images.githubusercontent.com/86318284/200549788-e2d6bb58-26d0-4b77-bcdd-0abd406bb3be.png)

2022-11-08 11:17 UTC, Nemwel-Boniface commented on index.html
> +    </section>
- [ ] Kindly check that the margins used in this section actually match the ones provided in the Figma design. Currently the margins/ padding right used in this section do not match the ones used in the Figma design. Kindlu make this change.

**This is how your design currently looks like:**

![image](https://user-images.githubusercontent.com/86318284/200550458-8b4b89c4-8f2b-4e5e-97c5-5ac173c5e9f9.png)

**This is the desired design:**

![image](https://user-images.githubusercontent.com/86318284/200550574-e0f4650d-ee2f-40a2-8afc-f33baacb937e.png)

2022-11-09 11:31 UTC, emmiiorji requested changes
Hi @Thinus01, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow
- Some requested changes have been implemented


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 11:31 UTC, emmiiorji commented on style.css
> +  align-items: center;
You have put in great effort to implement the changes requested by the previous reviewer. As pointed out by him, kindly note that this milestone is not isolated from the mobile version of the website but uses media queries to style it in order to display properly on desktop devices.

The website is expected to be responsive until the desktop size.

2022-11-09 11:31 UTC, emmiiorji commented on style.css
> +}
As pointed out by the previous reviewer, kindly fit the elements of the page properly to fit the container such that there's no horizontal scrolls.

Your design:
![image](https://user-images.githubusercontent.com/20554583/200819180-8e949a7e-147f-47fb-b783-a70265dc51ee.png)



Figma deisgn:
![image](https://user-images.githubusercontent.com/20554583/200818686-1e9ef5b4-b927-470e-9770-455a5ca9ff9a.png)

2022-11-11 19:21 UTC, tugsem requested changes
## STATUS: REQUIRED CHANGES ♻️
Hi @Thinus01 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Highlights 🚀
✔️ Great job making some of the requested changes

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 19:21 UTC, tugsem commented on style.css
> +    top: 440px;
## Optional
- [ ] In larger screens, cards don't seem to be centered. Kindly fix that as it increase user experience.
![image](https://user-images.githubusercontent.com/91486791/201414658-45a02295-a446-4d54-a5e7-a16c17651bc3.png)

2022-11-11 23:14 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @Thinus01 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Nice job making your sections responsive!
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 23:15 UTC, merged