Feature
Thinus01/Desktop_Portfolio pull request #6
Opened 2022-11-24 17:15 UTC by Thinus01

When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.
Used a JavaScript array to store all of the information for all projects.
Updated the main page so that the projects section is created dynamically using the information stored in that JavaScript object. 
Implemented a popup window.

2022-11-24 19:33 UTC, vickymarz requested changes
Hi @Thinus01, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] I will strongly recommend you always write a well-descriptive branch name explaining the feature that you are working on. So instead of writing `feature`, you can write `pop-up` as a branch name which is more descriptive. Changing the branch name now will likely close the PR which is not desirable so please take note of this in your next project 😄 . 

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 19:33 UTC, vickymarz commented on javascript.js
> +            </li>
- [ ] Good job working on the popup 👍🏽 . When I clicked on the `See project` button on the desktop view, the popup user interface didn't display straight up, I have to scroll up to be able to see the popup UI, and also, the popup height is too much so I have to scroll down so much to see the popup , which I think is not a good user experience in my own opinion 😄 

The popup is also not showing up immediately on the mobile view, I will also have to scroll up to see the popup and the popup is not centered as well. Kindly ensure the popup is seen immediately after clicking the `See project` button which is a good user experience 👍🏽 


https://user-images.githubusercontent.com/63473584/203852191-2585d97e-84d9-41c8-bb11-cc83f542f6e6.mp4


https://user-images.githubusercontent.com/63473584/203853258-83a9ca82-87a5-4fa5-8170-e968bae2790b.mp4

I will strongly suggest you use `width : 100%` instead of `width: 100vw` and also `height: 100vh` instead of  `height: 614.6%;` which will help organise your popup UI and make it immediately visible without having to scroll 👍🏽

2022-11-25 08:14 UTC, Alfredbis29 requested changes
## Hello @Thinus01 ,
 I'm Alfred your reviewer for this PR :man_beard:
 
 Great work working on your project so far! :clap: There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ![](https://camo.githubusercontent.com/4f9601b422a77702aefe8e13485d2d5618cc0c30772eb2aa9f4129eac4757e06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) 

 ## Highlights
Great job setting up the correct linters :heavy_check_mark:
 Meaningful commit messages :heavy_check_mark:
 
 ##  Required Changes :black_circle: 
 

- [ ] You still look to be using the outdated Readme template; you should switch to the newer version. , I suggest you to use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.  so that your README will look professional :wink: 

 - [ ]  _Check the comments under the review._
 
 ## [Optional] suggestions
 

- [ ]  _Check the comments under the review._

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Cheers and Happy coding! :partying_face: :clap: :clap:

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me  in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 08:14 UTC, Alfredbis29 commented on style.css
>  @media (max-width: 820px) {
- [ ] As required for this project your popup should be responsive and should fit mobile and desktop sizes properly.but when we click on see button it lost it responsiveness , kindly fix this for your project to fit all requirements :wink:  :smile:

2022-11-25 18:08 UTC, jerryowusu requested changes
Hi @Thinus01 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so close](https://user-images.githubusercontent.com/65233860/204037348-656b8da5-e3cb-4659-982d-46ff61aac42c.gif)

 ## Highlights
All linters are passing :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 
Neat and organised code :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 18:08 UTC, jerryowusu commented on style.css
> +  }
The popup should be responsive and fits the mobile and desktop sizes properly just as shown in the design. Unfortunately, your popup is slightly different as stated by the previous reviewer. Kindly ensure that your popup displays just as depicted in the design. You can consider using width and height of 100%, as well as top, bottom, left, right of 0 to achieve this. :-1: 

 Your desktop design            |  The actual design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-25 17-49-48](https://user-images.githubusercontent.com/65233860/204036700-c304e48d-97b4-479c-ae57-0dac8184321c.png)  |  ![Screenshot from 2022-11-25 17-52-38](https://user-images.githubusercontent.com/65233860/204036688-2d84b94a-4f84-488f-9ca1-baba1ce7de38.png)


 Your mobile design            |  The actual design 
:-------------------------:|:-------------------------:
![Screenshot from 2022-11-25 17-53-24](https://user-images.githubusercontent.com/65233860/204036795-07d9c146-fafa-4b22-b1a6-49bfde42cbdb.png)  |  ![Screenshot from 2022-11-25 18-04-07](https://user-images.githubusercontent.com/65233860/204037152-8994ef72-227d-463a-a2b1-1ad0c9e21775.png)

2022-11-25 21:20 UTC, nicupop729 reviewed
Hello @Thinus01, 👋,

_This is an additional review as a result of the second opinion request._

First of all, please note that the first reviewer, @vickymarz, was supposed to invalidate your CRR for the following reasons:
- only 1 student pushed commits in a pair-programming activity;
- the PR does not have a meaningful and descriptive title;
- the branch does not have a meaningful and descriptive name;
- before the first review, you were still using the old README;

Please make sure to ensure that the above invalidation reasons won't repeat again during the Microverse program.

I couldn't find the reasons that the last reviewer mentioned, I think that the pop-up is responsive enough and the content is fitting the pop-up. I think that your project can be approved.

As an optional suggestion, I would recommend you display the pop-up all the time from the top of the page, as now the user needs to scroll to find it. This aspect was also mentioned by the first reviewer, but unfortunately, you didn't fix the issue.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it manually so this could take a few hours!

Keep rocking 🚀!

2022-11-26 02:17 UTC, merged